### ISSUE TITLE
Modifying Templates

### ISSUE THREAD

**Issue by souhailmerroun** [pingpong-labs/generators#10]
After i 
php artisan vendor:publish --provider="Pingpong\Generators\GeneratorsServiceProvider"
The config file move successfully, but the template file doesn't move. I get no errors.

**Comment by trong291990** [comment]
Open file app/config/generators.php, change the value to your folder : 
`return [
    'template_path' => resource_path('pingpong/generators/stubs')
];`

Then in resource path, create that folder, and run vendor publish again
