### ISSUE TITLE
FatalErrorException

### ISSUE THREAD

**Issue by ummira** [pingpong-labs/generators#3]
runnning:
php artisan generate:migration create_users_table
i got:
 [Symfony\Component\Debug\Exception\FatalErrorException]
  Method Pingpong\Generators\Stub::__toString() must not throw an exception

but running php artisan make:migration create_users_table
ok

**Comment by gravitano** [comment]
I've fixed this issue via this commit https://github.com/pingpong-labs/sky/commit/5705abf37c42462b636ec86ab1c7b82c204c1161. And will pushed to this repository soon. Thanks!

**Comment by ummira** [comment]
thank you
can you tell me how you debug,
I can't finf throw problem with regular exception...

Il 08/07/2015 06:40, Gravitano ha scritto:

**Comment by gravitano** [comment]
Just basic debugging. If using artisan, you can add `-v` option to see the error trace is something went wrong.
