### ISSUE TITLE
Support foregin key and select option ?

### ISSUE THREAD

**Issue by trong291990** [pingpong-labs/generators#4]
Does this package support generate a select option box from relation table ?
For example : 
php artisan generate:scaffold task --fields="name:string, description=text, type=TypeObject" --prefix=admin

**Comment by gravitano** [comment]
Hi @trong291990, currently this package is not supported foreign key and select option. But, after I got this issue, maybe I would add this feature to new version of pingpong/generators. Thanks!

**Comment by trong291990** [comment]
:+1:
