### ISSUE TITLE
generate:scaffold [ErrorException] file_get_contents : row.stub failed to open stream: Invalid argument

### ISSUE THREAD

**Issue by fishmad** [pingpong-labs/generators#5]
Laravel 5.1.7 (LTS)
Pingpong/generators 2.1.4
1. Run this console command: php artisan generate:scaffold shed
2. Selecting Yes to all prompts - 
   except: Do you want to create a master view? (because I already have one).

Everything runs smoothly.

But
1. Run this console command: php artisan generate:scaffold shed --fields="name:string, slug:string, description:text"
2. Selecting Yes to all prompts - 
   except: Do you want to create a master view? (because I already have one).
   ......
   ......
   ......
   Migrated: 2015_07_18_105117_create_sheds_table
   Do you want to create master view? (yes/no) [no]:
   
   > n
   > Do you want to create view resources? (yes/no) [no]:
   > y
   
   [ErrorException]
   file_get_contents(C:\XAMPP-Portable\xampp\htdocs\laravel51plus\resources/pingpong/generators/stubs/C:\XAMPP-Portable\xampp\htdocs\larav
   el51plus\vendor\pingpong\generators\FormDumpers/../Stubs/scaffold/row.stub): failed to open stream: Invalid argument

C:\XAMPP-Portable\xampp\htdocs\laravel51plus>

**Comment by gravitano** [comment]
Hi @fishmad, are you still get this error ? Last time I use this package, everything is okay and there is no errors.

**Comment by gravitano** [comment]
Hi @fishmad, this error has solved in version 2.1.5. Thanks!

**Comment by fishmad** [comment]
Thumbs up.
