### ISSUE TITLE
Using in Modules

### ISSUE THREAD

**Issue by ghost** [pingpong-labs/generators#7]
Hello @gravitano ,

how can I use your generators with your module plugin ?

Example:
php artisan generate:scaffold user

How can I execute this for a module ?

Greetings!

**Comment by ghost** [comment]
No answer ?

**Comment by gravitano** [comment]
Hi, sorry for make you waiting the answer. Currently, this package can not use within my modules package. I don't know. Maybe, I would add this feature in the next release of pingpong/sky package. Thanks!

**Comment by ghost** [comment]
Okay! This feature is helpul. Currently I generate in a dummy project and copy all manuel to module project.
